project:
  type: website
  output-dir: docs

website:
  title: "Yeji Sohn"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Projects"
        href: projects.qmd
      - text: "Resume"
        href: about.qmd
      - text: "Blog"
        href: blog.qmd
    right:
      - icon: github
        href: https://github.com/dd5124

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



