project:
  type: website

website:
  title: "Yeji Sohn"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Projects"
        href: projects.qmd
      - text: "Resume"
        href: about.qmd
      - text: "Blog"
        href: blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



